#!/usr/bin/env python3
"""Generate a deterministic repository tree for documentation."""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "PROJECT-TREE.txt"
EXCLUDED_DIRS = {
    ".git",
    ".idea",
    ".vscode",
    "node_modules",
    "dist",
    "target",
    "coverage",
    "playwright-report",
    "test-results",
    "blob-report",
    "__pycache__",
}
EXCLUDED_FILES = {".DS_Store", "Thumbs.db"}


def entries(directory: Path) -> list[Path]:
    return sorted(
        (
            path
            for path in directory.iterdir()
            if path.name not in EXCLUDED_FILES
            and not (path.is_dir() and path.name in EXCLUDED_DIRS)
        ),
        key=lambda path: (not path.is_dir(), path.name.lower()),
    )


def render(directory: Path, depth: int = 0) -> list[str]:
    lines: list[str] = []
    for path in entries(directory):
        indent = "  " * depth
        kind = "DIR" if path.is_dir() else "FILE"
        lines.append(f"{indent}[{kind}] {path.name}")
        if path.is_dir():
            lines.extend(render(path, depth + 1))
    return lines


def main() -> None:
    lines = [
        "# Generated by scripts/build_project_tree.py",
        "# Excludes dependencies, build output, coverage and test reports.",
        "",
        *render(ROOT),
        "",
    ]
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
