use serde::{Deserialize, Serialize};

#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Phase {
    Idle,
    Preparing,
    Focusing,
    Paused,
    Complete,
    Abandoned,
    Debrief,
    Break,
}

impl Phase {
    pub fn as_str(self) -> &'static str {
        match self {
            Phase::Idle => "idle",
            Phase::Preparing => "preparing",
            Phase::Focusing => "focusing",
            Phase::Paused => "paused",
            Phase::Complete => "complete",
            Phase::Abandoned => "abandoned",
            Phase::Debrief => "debrief",
            Phase::Break => "break",
        }
    }

    pub fn is_terminal(self) -> bool {
        matches!(self, Phase::Complete | Phase::Abandoned)
    }
}

#[derive(Debug, PartialEq, Eq)]
pub enum SessionError {
    InvalidTransition,
}

#[derive(Clone, Debug)]
pub struct SessionState {
    pub id: Option<String>,
    pub mission_id: Option<String>,
    pub phase: Phase,
    pub mission_title: String,
    pub victory_condition: String,
    pub planned_duration_secs: u64,
    pub started_at_ms: Option<i64>,
    pub total_paused_ms: i64,
    pub pause_started_at_ms: Option<i64>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SessionSnapshot {
    pub phase: Phase,
    pub mission_title: String,
    pub victory_condition: String,
    pub planned_duration_secs: u64,
    pub started_at_ms: Option<i64>,
    pub total_paused_ms: i64,
    pub pause_started_at_ms: Option<i64>,
    pub remaining_secs: u64,
}

impl SessionState {
    pub fn idle() -> Self {
        Self {
            id: None,
            mission_id: None,
            phase: Phase::Idle,
            mission_title: String::new(),
            victory_condition: String::new(),
            planned_duration_secs: 0,
            started_at_ms: None,
            total_paused_ms: 0,
            pause_started_at_ms: None,
        }
    }

    /// START — begin a new session's preparation. `id`/`mission_id` are the
    /// durable identity (generated by the caller). The timer does not run yet;
    /// `begin` stamps the real start once preparation finishes.
    pub fn start(
        &mut self,
        id: String,
        mission_id: String,
        mission: String,
        victory: String,
        planned_secs: u64,
    ) -> Result<(), SessionError> {
        if !matches!(
            self.phase,
            Phase::Idle | Phase::Complete | Phase::Abandoned | Phase::Break
        ) {
            return Err(SessionError::InvalidTransition);
        }
        self.id = Some(id);
        self.mission_id = Some(mission_id);
        self.phase = Phase::Preparing;
        self.mission_title = mission;
        self.victory_condition = victory;
        self.planned_duration_secs = planned_secs;
        self.started_at_ms = None;
        self.total_paused_ms = 0;
        self.pause_started_at_ms = None;
        Ok(())
    }

    /// PREPARATION_FINISHED — the companion has formed up; start the timer.
    pub fn begin(&mut self, now_ms: i64) -> Result<(), SessionError> {
        if self.phase != Phase::Preparing {
            return Err(SessionError::InvalidTransition);
        }
        self.phase = Phase::Focusing;
        self.started_at_ms = Some(now_ms);
        Ok(())
    }

    /// CANCEL — abort during preparation, before the timer ran.
    pub fn cancel(&mut self) -> Result<(), SessionError> {
        if self.phase != Phase::Preparing {
            return Err(SessionError::InvalidTransition);
        }
        *self = SessionState::idle();
        Ok(())
    }

    pub fn pause(&mut self, now_ms: i64) -> Result<(), SessionError> {
        if self.phase != Phase::Focusing {
            return Err(SessionError::InvalidTransition);
        }
        self.phase = Phase::Paused;
        self.pause_started_at_ms = Some(now_ms);
        Ok(())
    }

    pub fn resume(&mut self, now_ms: i64) -> Result<(), SessionError> {
        let Some(paused_at) = self.pause_started_at_ms else {
            return Err(SessionError::InvalidTransition);
        };
        if self.phase != Phase::Paused {
            return Err(SessionError::InvalidTransition);
        }
        self.total_paused_ms += now_ms - paused_at;
        self.pause_started_at_ms = None;
        self.phase = Phase::Focusing;
        Ok(())
    }

    /// COMPLETE — TIMER_ELAPSED or COMPLETE_EARLY. Idempotent: only Focusing or
    /// Paused can complete, so a second call is rejected and no duplicate occurs.
    pub fn complete(&mut self) -> Result<(), SessionError> {
        if !matches!(self.phase, Phase::Focusing | Phase::Paused) {
            return Err(SessionError::InvalidTransition);
        }
        self.phase = Phase::Complete;
        self.pause_started_at_ms = None;
        Ok(())
    }

    /// ABANDON — interrupt an active session without a completion reward. The
    /// flow that captures a reason is VIGIL-008; this is only the transition.
    pub fn abandon(&mut self) -> Result<(), SessionError> {
        if !matches!(self.phase, Phase::Focusing | Phase::Paused) {
            return Err(SessionError::InvalidTransition);
        }
        self.phase = Phase::Abandoned;
        self.pause_started_at_ms = None;
        Ok(())
    }

    /// OPEN_DEBRIEF / CAPTURE_REASON — after a watch ends, move to the optional
    /// debrief step. The finished row is already persisted; this only changes phase.
    pub fn open_debrief(&mut self) -> Result<(), SessionError> {
        if !matches!(self.phase, Phase::Complete | Phase::Abandoned) {
            return Err(SessionError::InvalidTransition);
        }
        self.phase = Phase::Debrief;
        Ok(())
    }

    /// RECORD — the debrief is captured; return to Idle. The caller persists the
    /// debrief fields to the finished row before calling this.
    pub fn record(&mut self) -> Result<(), SessionError> {
        if self.phase != Phase::Debrief {
            return Err(SessionError::InvalidTransition);
        }
        *self = SessionState::idle();
        Ok(())
    }

    /// START_BREAK — take an optional recovery break after a completed watch. The
    /// finished session is already persisted; the break carries no mission and is
    /// never recorded. Never forced — the UI only offers it.
    pub fn start_break(&mut self, now_ms: i64, break_secs: u64) -> Result<(), SessionError> {
        // Rest belongs between watches, not during one.
        if !matches!(self.phase, Phase::Idle | Phase::Complete) {
            return Err(SessionError::InvalidTransition);
        }
        *self = SessionState::idle();
        self.phase = Phase::Break;
        self.planned_duration_secs = break_secs;
        self.started_at_ms = Some(now_ms);
        Ok(())
    }

    /// END_BREAK — the break elapsed or was skipped; return to Idle.
    pub fn end_break(&mut self) -> Result<(), SessionError> {
        if self.phase != Phase::Break {
            return Err(SessionError::InvalidTransition);
        }
        *self = SessionState::idle();
        Ok(())
    }

    /// Exclude an away interval (machine sleep, a frozen process) from focused
    /// time by accounting for it exactly like paused time. Only the user asks for
    /// this — detection alone never removes focus time.
    pub fn discount_gap(&mut self, gap_ms: i64) -> Result<(), SessionError> {
        if !matches!(self.phase, Phase::Focusing | Phase::Paused) {
            return Err(SessionError::InvalidTransition);
        }
        if gap_ms > 0 {
            self.total_paused_ms += gap_ms;
        }
        Ok(())
    }

    pub fn reset(&mut self) {
        *self = SessionState::idle();
    }

    pub fn remaining_secs(&self, now_ms: i64) -> u64 {
        let Some(started) = self.started_at_ms else {
            return self.planned_duration_secs;
        };
        let live_pause = match self.pause_started_at_ms {
            Some(p) => now_ms - p,
            None => 0,
        };
        let paused = self.total_paused_ms + live_pause;
        let elapsed_ms = (now_ms - started - paused).max(0);
        let elapsed_secs = (elapsed_ms / 1000) as u64;
        self.planned_duration_secs.saturating_sub(elapsed_secs)
    }

    /// Seconds actually focused so far (elapsed minus paused), capped at planned.
    pub fn focused_secs(&self, now_ms: i64) -> u64 {
        self.planned_duration_secs
            .saturating_sub(self.remaining_secs(now_ms))
    }

    pub fn snapshot(&self, now_ms: i64) -> SessionSnapshot {
        SessionSnapshot {
            phase: self.phase,
            mission_title: self.mission_title.clone(),
            victory_condition: self.victory_condition.clone(),
            planned_duration_secs: self.planned_duration_secs,
            started_at_ms: self.started_at_ms,
            total_paused_ms: self.total_paused_ms,
            pause_started_at_ms: self.pause_started_at_ms,
            remaining_secs: self.remaining_secs(now_ms),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn preparing(planned: u64) -> SessionState {
        let mut s = SessionState::idle();
        s.start(
            "sid".into(),
            "mid".into(),
            "Ship slice".into(),
            String::new(),
            planned,
        )
        .unwrap();
        s
    }

    fn started() -> SessionState {
        let mut s = preparing(1500);
        s.begin(0).unwrap();
        s
    }

    #[test]
    fn start_from_idle_enters_preparing_without_starting_the_timer() {
        let s = preparing(1500);
        assert_eq!(s.phase, Phase::Preparing);
        assert_eq!(s.started_at_ms, None);
        assert_eq!(s.id.as_deref(), Some("sid"));
        assert_eq!(s.remaining_secs(999_000), 1500); // full duration while preparing
    }

    #[test]
    fn begin_moves_preparing_to_focusing_and_stamps_start() {
        let mut s = preparing(1500);
        s.begin(1_000).unwrap();
        assert_eq!(s.phase, Phase::Focusing);
        assert_eq!(s.started_at_ms, Some(1_000));
        assert_eq!(s.remaining_secs(61_000), 1440); // 60s elapsed
    }

    #[test]
    fn begin_rejected_unless_preparing() {
        let mut s = SessionState::idle();
        assert!(matches!(s.begin(0), Err(SessionError::InvalidTransition)));
    }

    #[test]
    fn cancel_returns_preparing_to_idle() {
        let mut s = preparing(1500);
        s.cancel().unwrap();
        assert_eq!(s.phase, Phase::Idle);
        assert_eq!(s.id, None);
    }

    #[test]
    fn cancel_rejected_unless_preparing() {
        let mut s = started();
        assert!(matches!(s.cancel(), Err(SessionError::InvalidTransition)));
    }

    #[test]
    fn start_rejected_from_focusing() {
        let mut s = started();
        assert!(matches!(
            s.start("x".into(), "y".into(), "b".into(), String::new(), 1500),
            Err(SessionError::InvalidTransition)
        ));
    }

    #[test]
    fn start_allowed_again_after_complete_or_abandon() {
        let mut s = started();
        s.complete().unwrap();
        assert!(s
            .start("a".into(), "b".into(), "next".into(), String::new(), 900)
            .is_ok());
        let mut s2 = started();
        s2.abandon().unwrap();
        assert!(s2
            .start("a".into(), "b".into(), "next".into(), String::new(), 900)
            .is_ok());
    }

    #[test]
    fn pause_then_resume_excludes_paused_time_from_elapsed() {
        let mut s = started();
        s.pause(60_000).unwrap();
        assert_eq!(s.phase, Phase::Paused);
        s.resume(120_000).unwrap();
        assert_eq!(s.total_paused_ms, 60_000);
        // 180s wall - 60s paused = 120s focused -> 1500 - 120 = 1380
        assert_eq!(s.remaining_secs(180_000), 1380);
        assert_eq!(s.focused_secs(180_000), 120);
    }

    #[test]
    fn pause_rejected_when_not_focusing() {
        let mut s = SessionState::idle();
        assert!(matches!(s.pause(1), Err(SessionError::InvalidTransition)));
    }

    #[test]
    fn resume_rejected_when_not_paused() {
        let mut s = started();
        assert!(matches!(s.resume(1), Err(SessionError::InvalidTransition)));
    }

    #[test]
    fn complete_from_focusing_or_paused() {
        let mut s = started();
        s.complete().unwrap();
        assert_eq!(s.phase, Phase::Complete);

        let mut p = started();
        p.pause(1_000).unwrap();
        p.complete().unwrap();
        assert_eq!(p.phase, Phase::Complete);
    }

    #[test]
    fn complete_is_idempotent() {
        let mut s = started();
        s.complete().unwrap();
        assert!(matches!(s.complete(), Err(SessionError::InvalidTransition)));
    }

    #[test]
    fn abandon_from_focusing_or_paused() {
        let mut s = started();
        s.abandon().unwrap();
        assert_eq!(s.phase, Phase::Abandoned);

        let mut p = started();
        p.pause(1_000).unwrap();
        p.abandon().unwrap();
        assert_eq!(p.phase, Phase::Abandoned);
    }

    #[test]
    fn abandon_rejected_when_idle_or_preparing() {
        let mut s = SessionState::idle();
        assert!(matches!(s.abandon(), Err(SessionError::InvalidTransition)));
        let mut p = preparing(1500);
        assert!(matches!(p.abandon(), Err(SessionError::InvalidTransition)));
    }

    #[test]
    fn open_debrief_from_complete_or_abandoned() {
        let mut c = started();
        c.complete().unwrap();
        c.open_debrief().unwrap();
        assert_eq!(c.phase, Phase::Debrief);
        // The mission survives into the debrief so the caller can persist against it.
        assert_eq!(c.id.as_deref(), Some("sid"));

        let mut a = started();
        a.abandon().unwrap();
        a.open_debrief().unwrap();
        assert_eq!(a.phase, Phase::Debrief);
    }

    #[test]
    fn open_debrief_rejected_unless_finished() {
        let mut s = started();
        assert!(matches!(
            s.open_debrief(),
            Err(SessionError::InvalidTransition)
        ));
        let mut i = SessionState::idle();
        assert!(matches!(
            i.open_debrief(),
            Err(SessionError::InvalidTransition)
        ));
    }

    #[test]
    fn record_returns_debrief_to_idle() {
        let mut s = started();
        s.complete().unwrap();
        s.open_debrief().unwrap();
        s.record().unwrap();
        assert_eq!(s.phase, Phase::Idle);
        assert_eq!(s.id, None);
    }

    #[test]
    fn record_rejected_unless_debriefing() {
        let mut s = started();
        s.complete().unwrap();
        assert!(matches!(s.record(), Err(SessionError::InvalidTransition)));
    }

    #[test]
    fn start_break_from_complete_runs_a_timer_without_a_mission() {
        let mut s = started();
        s.complete().unwrap();
        s.start_break(1_000_000, 300).unwrap();
        assert_eq!(s.phase, Phase::Break);
        assert_eq!(s.id, None); // a break carries no mission
        assert_eq!(s.remaining_secs(1_060_000), 240); // 60s into a 300s break
    }

    #[test]
    fn start_break_allowed_from_idle_but_not_during_a_watch() {
        let mut idle = SessionState::idle();
        assert!(idle.start_break(0, 300).is_ok());
        // Not while a watch is running.
        let mut focusing = started();
        assert!(matches!(
            focusing.start_break(0, 300),
            Err(SessionError::InvalidTransition)
        ));
    }

    #[test]
    fn end_break_returns_to_idle() {
        let mut s = started();
        s.complete().unwrap();
        s.start_break(0, 300).unwrap();
        s.end_break().unwrap();
        assert_eq!(s.phase, Phase::Idle);
    }

    #[test]
    fn end_break_rejected_unless_breaking() {
        let mut s = SessionState::idle();
        assert!(matches!(
            s.end_break(),
            Err(SessionError::InvalidTransition)
        ));
    }

    #[test]
    fn a_watch_can_start_straight_from_a_break() {
        let mut s = started();
        s.complete().unwrap();
        s.start_break(0, 300).unwrap();
        assert!(s
            .start("a".into(), "b".into(), "m".into(), String::new(), 900)
            .is_ok());
        assert_eq!(s.phase, Phase::Preparing);
    }

    #[test]
    fn discounting_a_sleep_gap_removes_it_from_focused_time() {
        let mut s = started(); // focusing, started at 0, planned 1500s
                               // Ten minutes of wall clock passed...
        assert_eq!(s.focused_secs(600_000), 600);
        // ...but five of them were the machine asleep.
        s.discount_gap(300_000).unwrap();
        assert_eq!(s.focused_secs(600_000), 300);
        assert_eq!(s.remaining_secs(600_000), 1200);
    }

    #[test]
    fn discount_gap_rejected_outside_a_running_watch() {
        let mut idle = SessionState::idle();
        assert!(matches!(
            idle.discount_gap(1_000),
            Err(SessionError::InvalidTransition)
        ));
    }

    #[test]
    fn remaining_never_underflows_past_zero() {
        let mut s = preparing(60);
        s.begin(0).unwrap();
        assert_eq!(s.remaining_secs(999_000), 0);
    }
}
